### ISSUE TITLE
Compatibility with IntelliJ IDEA 2023.3.+

### ISSUE THREAD

**Issue by victoragung** [dirkgroot/structurizr-dsl-intellij-plugin#103]
Would it be possible for the plugin to be published to support the newer versions of Jetbrains IDEs?

**Comment by dobe** [comment]
some details from the logs:

```
Plugin 'Structurizr DSL Language Support' (version '0.3.2') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.300
```

**Comment by nathan-maves** [comment]
I really don't want to rollback to a previous version.  Can we get a quick bump on this?

**Comment by dirkgroot** [comment]
My apologies for the delay, I haven't really gotten around to giving this plugin some much needed attention. Unfortunately, my unit testing setup led to recurring compatibility issues when upgrading to newer IntelliJ versions. So to update the plugin to IntelliJ 2023.3 wasn't as easy as changing a few Gradle properties.

I've now reverted my unit testing setup to the default setup, as per the [Platform plugin template](https://github.com/JetBrains/intellij-platform-plugin-template), so future updates should be a lot less painful 😄.

**Comment by dirkgroot** [comment]
I'm going to publish the updated version today. As every version needs approval from JetBrains, I expect the new version to be available in a few days maximum.
