### ISSUE TITLE
Identifier completion

### ISSUE THREAD

**Issue by neopaf** [dirkgroot/structurizr-dsl-intellij-plugin#105]
and whatever possible to borrow from a [peer project](https://github.com/ambalashov/structurizr-idea-plugin) that works good?

Author ignores my reports, maybe you're more open?

Thanks for awesome plugin!

**Comment by dirkgroot** [comment]
Thanks for bringing this up, and apologies for my late answer.

I'm currently in the process of rewriting the lexer/parser (again), applying what I've learned so far. Hopefully adding code completion and other useful features will become a lot easier when this is done. My available time is limited, so this could take a while.

**Comment by dirkgroot** [comment]
I'm closing this issue, as it is a duplicate of #71.
