### ISSUE TITLE
After adding alpha channel plugins, structurizr is not found on the list of plugins

### ISSUE THREAD

**Issue by MaciejG** [dirkgroot/structurizr-dsl-intellij-plugin#15]
After adding alpha channel plugins (https://plugins.jetbrains.com/plugins/alpha/list), structurizr is not found on the list of plugins even after IntelliJ restart. Other plugins from that channel such as "ZenUml" are on the list.

**Comment by dirkgroot** [comment]
Oh, that's odd. Are you sure you have the "Marketplace" tab active when you're searching for structurizr?

<img width="678" alt="image" src="https://user-images.githubusercontent.com/3872163/213237424-08f54f54-1b72-46fa-b3a8-4323dd2f00f3.png">

**Comment by dirkgroot** [comment]
Also, what version of IntelliJ are you using?

**Comment by MaciejG** [comment]
Hi. That was it. I downloaded all your code. Built the plugin and tried to add it as file. IntelliJ complained that it's too old this time. I updated it and the plugin works. I can also find it now in marketplace. My bad. Jetbrains guys could list incompatible plugins from the marketplace. Or at least make some flag to display all. It's safe to close the issue.

**Comment by dirkgroot** [comment]
Cool! Thanks for trying this plugin out. Feel free to leave any feedback you have!
