### ISSUE TITLE
`themes` token missing

### ISSUE THREAD

**Issue by rgustafson-ie** [dirkgroot/structurizr-dsl-intellij-plugin#48]
The `view -> themes` elements is not recognized.

From the Structurizer [DSL](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#themes) and the [dsl tokens](https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/StructurizrDslTokens.java#L89) code.  If I compare tokens in the [.flex](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/blob/main/src/main/grammar/StructurizrDSL.flex), I see these tokens missing:
```
animationStep
dashed
default
font
image
kroki
logo
mermaid
name
plantuml
relationship
themes
this
```

A consequence of using an unrecognized token can be that attempts to format the file result in everything aligning in column 0, instead of properly indenting.

**Comment by dirkgroot** [comment]
Hi, thanks for your feedback! The linked PR should fix this. Please note that not all the keywords you mentioned will be highlighted as keywords, though using them will not break syntax highlighting.
