### ISSUE TITLE
Support "Comment with Line Comment" code action

### ISSUE THREAD

**Issue by rgustafson-ie** [dirkgroot/structurizr-dsl-intellij-plugin#49]
Please support using the "Comment with Line Comment" code action (i.e. `⌘/` on a Mac), and the similar Block action.  This is helpful when editing to quickly enable/disable blocks of DSL.  Currently one needs to place comments manually on each line.

The Structurizr [DSL Comments](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#comments) support both C-style and shell-style comments, so perhaps a setting and/or auto-detection of currently used style (first seen?).

**Comment by dirkgroot** [comment]
Hi, thanks again for your feedback 😃. The linked PR adds basic support for the "Comment with line/block comment" actions. Currently, it will always use `//` as the line comment prefix.
