### ISSUE TITLE
support "relationship styles"

### ISSUE THREAD

**Issue by ambition-consulting** [dirkgroot/structurizr-dsl-intellij-plugin#50]
hey, great work - already saves me so much time! however, there is a nasty problem with relationship styles, that breaks your nice highlighting and formatting: https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#relationship-style

**Comment by ambition-consulting** [comment]
I'm also having problem with relationship properties:

a -> b {
 url abc.com
}

**Comment by dirkgroot** [comment]
Hi, thanks for your feedback! The linked PR should fix both of the problems you're describing.
