### ISSUE TITLE
Lexer issue: CRLF expected got xy

### ISSUE THREAD

**Issue by Ntr0** [dirkgroot/structurizr-dsl-intellij-plugin#58]
I noticed some cases were the lexer does not get things right. 
Example:
```
workspace {
  model {
  }
}
```
Problem -> `CRLF expected, got 'model'` 
This can be "fixed" by adding quotes around an escaped quote: `workspace "\""`
It seems to be unrelated to the model keyword but an issue with quote detection, as in other occasions (e.g. after `softwareSystem`) adding the `"\""` fixes the lexer state.

**Comment by erstam** [comment]
same issue here

IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Non-Bundled Plugins:
    nl.dirkgroot.structurizr-dsl-plugin (0.3.1)

**Comment by dirkgroot** [comment]
Thanks for reporting this! I'm still struggling, dealing with the ambiguity of the Structurizr DSL language in the lexer and parser. Any tips on making this easier are very welcome!

**Comment by dirkgroot** [comment]
I'm not able to reproduce this issue with version 0.3.1 of the plugin. Could you describe the exact steps you take to reproduce this issue?

**Comment by erstam** [comment]
Hi @dirkgroot !

I have pinpointed the exact cause of this issue, at least for my case. The below images should help you sort it out.

I can describe a relationship without any tag:

![image](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/assets/90407741/228a280a-f194-4e55-97d2-f690d94bbcbb)

Or empty string tag which gives the same result:

![image](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/assets/90407741/4817f1d1-5fd4-45ea-9c48-aca5cc7c2621)

Or I can use some constant reference defined in my `common_definitions.dsl`:

![image](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/assets/90407741/0e066f8a-5385-4721-96df-10c70d04c8d8)

But using the constant value without putting it between quotes gives the error. However, it works DSL-wise.  It is a valid model and I can render it on my structurizr container without any problem.  So the quotes missing looks like a false positive.

![image](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/assets/90407741/b9c7af0d-b236-4708-bc00-baa419dd9cd3)

**Comment by erstam** [comment]
Moreover, the error message is vague regarding the exact cause of the issue

**Comment by dirkgroot** [comment]
Ah nice, thanks! I'll look into it.

While I think I understand why the language is so flexible, these kinds of "multiple ways to do 1 thing" (quotes are optional for strings that don't contain spaces) make it hard to account for every possible situation when creating lexers/parsers.

**Comment by FlorianGWE** [comment]
You got also the error if you do insert a manual newline with character '\' 

like 
`
   system = softwareSystem "name" \
             "long description" "TAGS" {
   }
`
