### ISSUE TITLE
Support for dynamic parallel

### ISSUE THREAD

**Issue by RedSlowpoke** [dirkgroot/structurizr-dsl-intellij-plugin#70]
The syntax highlint and indentation breaks when parallel used in dynamic view
to reproduce
just copy the snippet from cookbook https://github.com/structurizr/dsl/tree/master/docs/cookbook/dynamic-view-parallel
the highlighting is broken and even indentation
![Screenshot 2023-07-13 at 16 56 04](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/assets/484635/1bc21ecb-8ed5-437e-8621-4dbc58734919)

**Comment by cristianlorand** [comment]
Hi, the error I'm getting is 
> <statement> expected, got '}'
I'm assuming this is an unsupported feature (as of 22.08.2023). Once pushed to structurizr (on-prem) it renders correctly.

**Comment by RedSlowpoke** [comment]
What do you mean unsupported and which feature?
The parallel in dynamic views? It's clearly supported in lite, cloud and on-premise.

**Comment by dirkgroot** [comment]
Sorry for the long delay, but this should be fixed in the next release, which I'm going to publish today.
