### ISSUE TITLE
Compatibility Issue with newer PyCharm builds

### ISSUE THREAD

**Issue by dorvak** [dirkgroot/structurizr-dsl-intellij-plugin#78]
According to PyCharm the most recent version is not compatible with more recent builds:

PyCharm 2023.2 (Professional Edition)
Build #PY-232.8660.197, built on July 26, 2023

It would be great if you could support the newest versions as well. Thanks in advance!

**Comment by dirkgroot** [comment]
I've published release [0.3.2](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin/releases/tag/v0.3.2), which makes this plugin compatible with IntelliJ 2023.2. This should fix this issue.

Plugin approval by JetBrains is in progress, so the new version should be available within PyCharm within a couple of working days.
